import { Module } from '../core/module';
import { random } from '../utils';

export class StarSkyModule extends Module {

  trigger() {
    this.createStarSky();
  }

  toHTML() {
    return `<li class="menu-item" data-type="${this.type}">${this.text}</li>`;
  }

  createStarSky() {
    this.container = document.createElement('div');
    this.container.id = 'starSkyContainer';
    document.body.appendChild(this.container);

    this.container.style.position = 'fixed';
    this.container.style.top = '0';
    this.container.style.left = '0';
    this.container.style.width = '100%';
    this.container.style.height = '100%';
    this.container.style.zIndex = '-1';
    this.container.style.overflow = 'hidden';
    document.body.style.backgroundColor = 'black';

    const canvas = document.createElement('canvas');
    canvas.id = 'starSkyCanvas';
    this.container.appendChild(this.canvas);

    this.canvas.width = this.container.offsetWidth;
    this.canvas.height = this.container.offsetHeight;

    const ctx = canvas.getContext('2d');

    const stars = this.createStars(200); //this.createStars.bind(this)(200);

    const animate = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      stars.forEach((star) => {
        star.update();
        star.draw(ctx);
      });
      requestAnimationFrame(animate);
    };
    animate();
  }

  createStars(count) {
    const stars = [];
    for (let i = 0; i < count; i++) {
      const x = random(0, window.innerWidth);
      const y = random(0, window.innerHeight);
      const radius = random(1, 3);
      const speed = random(0.1, 0.5);
      stars.push(new Star(x, y, radius, speed));
    }
    return stars;
  }
}

class Star {
  constructor(x, y, radius, speed) {
    this.x = x;
    this.y = y;
    this.radius = radius;
    this.speed = speed;
    this.alpha = 1;
  }

  update() {
    this.y += this.speed;
    if (this.y > window.innerHeight) {
      this.y = 0;
      this.x = random(0, window.innerWidth);
    }
  }

  draw(ctx) {
    ctx.beginPath();
    ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(255, 255, 255, ${this.alpha})`;
    ctx.fill();
    ctx.closePath();
  }
}
